name: cpp-aquachain
version: master
summary: blockchain app platform
description: Aquachain C++ project

grade: devel
confinement: devmode

apps:
  aqua:
    command: aqua
  aquavm:
    command: aquavm

parts:
  cpp-aquachain:
    source: .
    source-type: git
    plugin: cmake
    build-packages:
      - build-essential
      - libgmp-dev
      - libleveldb-dev
